# config for action-label-syncer
# https://github.com/micnncim/action-label-syncer

# pr category labels
- name: pr-category/enhancement
  description: Product enhancement。機能の追加・改善。
  color: 88dd5d
- name: pr-category/improvement
  description: Productiviety improvement。開発効率改善、運用効率改善、リファクタ、ドキュメンテーション。
  color: fbca04
- name: pr-category/hotfix
  description: Hot fix。本番環境に流出した不具合の修正。
  color: e99695
- name: pr-category/bugfix
  description: Bug fix。QAやレビューで発見された不具合の修正。
  color: 1d76db
- name: pr-category/misc
  description: Miscellaneous。その他。
  color: cfd3d7
- name: pr-category/bump
  description: Bump version。バージョンの更新。
  color: fff5ee

# proto change labels
- name:  proto-changes/breaking
  description: Breaking change of protocol。プロトコル定義に後方互換性のない変更。proto のメジャーバージョンが上がる。
  color: d93f0b
- name:  proto-changes/compatible
  description: Compatible change of protocol。プロトコル定義に後方互換性のある変更。proto のマイナーバージョンが上がる。
  color: 88dd5d
- name:  proto-changes/dependency
  description: Dependency change of protocol。プロトコル定義から生成するクライアントライブラリの依存関係変更。proto のパッチバージョンが上がる。
  color: cfd3d7
