name-template: 'proto/v$RESOLVED_VERSION'
tag-template: 'proto/v$RESOLVED_VERSION'
categories:
  - title: ':boom: Breaking Changes'
    labels:
      - 'category/breakingchange'
  - title: ':sparkles: Product Enhancements'
    labels:
      - 'category/enhancement'
  - title: ':zap: Productivity Improvements'
    labels:
      - 'category/improvement'
  - title: ':ambulance: Hot Fixes'
    labels:
      - 'category/hotfix'
  - title: ':bug: Bug Fixes'
    labels:
      - 'category/bugfix'
  - title: 'Miscellaneous'
    labels:
      - 'category/misc'
version-resolver:
  major:
    labels:
      - 'proto/version/major'
  minor:
    labels:
      - 'proto/version/minor'
  patch:
    labels:
      - 'proto/version/patch'
  default: patch
include-labels:
  - proto/category/breakingchange
  - proto/category/compatiblechange
  - proto/category/dependencychange
template: |
  ## What’s Changed

  $CHANGES

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION
