version: v1

labels:
  - label: 'proto/versioning/bump-major'
    sync: true
    matcher:
      body: '\[x\] プロトコル定義に後方互換性のある変更'
  - label: 'proto/versioning/bump-minor'
    sync: true
    matcher:
      body: '- \[x\] プロトコル定義に後方互換性のない変更'
  - label: 'proto/versioning/bump-patch'
    sync: true
    matcher:
      body: '- \[x\] プロトコル定義から生成するクライアントライブラリの依存関係変更'

checks:
  - context: "Protocol semantic versioning label check"
    description:
      success: "Ready for review & merge."
      failure: "Missing protocol semantic versioning labels."
    labels:
      any:
        - proto/versioning/bump-major
        - proto/versioning/bump-minor
        - proto/versioning/bump-patch
