name-template: 'deploy-$RESOLVED_VERSION'
tag-template: 'deploy-$RESOLVED_VERSION'
categories:
  - title: ':boom: Breaking Changes'
    labels:
      - 'category/breakingchange'
  - title: ':sparkles: Product Enhancements'
    labels:
      - 'category/enhancement'
  - title: ':zap: Productivity Improvements'
    labels:
      - 'category/improvement'
  - title: ':ambulance: Hot Fixes'
    labels:
      - 'category/hotfix'
  - title: ':bug: Bug Fixes'
    labels:
      - 'category/bugfix'
  - title: 'Miscellaneous'
    labels:
      - 'category/misc'
template: |
  ## What’s Changed

  $CHANGES

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...deploy-$RESOLVED_VERSION
