name-template: proto/v$RESOLVED_VERSION
tag-template: proto/v$RESOLVED_VERSION
tag-prefix: proto/v
categories:
  - title: ':sparkles: Product Enhancements'
    labels:
      - pr-category/enhancement
  - title: ':zap: Productivity Improvements'
    labels:
      - pr-category/improvement
  - title: ':ambulance: Hot Fixes'
    labels:
      - pr-category/hotfix
  - title: ':bug: Bug Fixes'
    labels:
      - pr-category/bugfix
  - title: 'Miscellaneous'
    labels:
      - pr-category/misc
version-resolver:
  major:
    labels:
      -  proto-changes/breaking
  minor:
    labels:
      -  proto-changes/compatible
  patch:
    labels:
      -  proto-changes/dependency
  default: patch
include-labels:
  -  proto-changes/breaking
  -  proto-changes/compatible
  -  proto-changes/dependency
template: |
  ## What’s Changed

  $CHANGES

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...proto/v$RESOLVED_VERSION
