name: Auto assign labels to pull requests

on:
  workflow_call:

jobs:
  auto_assign_labels_to_pr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      statuses: write
      checks: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Auto assign labels to pull requests
        uses: fuxingloh/multi-labeler@v2
        with:
          config-path: .github/labeler.yaml
