name: Sync labels

on:
  workflow_call:

jobs:
  sync_labels:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Sync labels
        uses: micnncim/action-label-syncer@v1
        with:
          manifest: .github/labels.yaml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
