name: Publish gem

inputs:
  gem_name:
    description: A name of the gem to be published
    required: true
    type: string

runs:
  using: composite
  steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup ruby
      uses: ruby/setup-ruby@v1

    - name: Configure gem credentials
      run: |
        mkdir -p ~/.gem
        touch ~/.gem/credentials
        chmod 600 ~/.gem/credentials
        echo -e "---\n:github: Bearer ${{ secrets.GITHUB_TOKEN }}" > ~/.gem/credentials

    - name: Build and push gem
      run: |
        rm -f ${{ inputs.gem_name }}-*.gem
        gem build ${{ inputs.gem_name }}.gemspec
        gem push --key github --host https://rubygems.pkg.github.com/ych-tnk ${{ inputs.gem_name }}-*.gem
