name: _Publish latest draft release

on:
  workflow_call:
    inputs:
      prerelease:
        description: A flag whether the release is pre-release or not
        required: true
        type: boolean
      version:
        description: The version to be associated with the published release
        required: false
        type: string

jobs:
  publish_release:
    runs-on: ubuntu-latest
    outputs:
      published_tag: ${{ steps.get_published_tag.outputs.tag_name }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check draft release
        id: check_draft_release
        run: |
          published="$(test -n "$(gh api /repos/{owner}/{repo}/releases --jq '.[] | select(.tag_name == "${{ inputs.version }}" and .draft == false)')" && echo 'true' || echo 'false')"
          if [ "${published}" == 'true' ]; then
            echo '::warning::The draft release publication skipped because the draft release has already been published.'
          fi
          echo "published=${published}" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Enable include-pre-releases
        if: inputs.prerelease == true
        run: |
          echo 'include-pre-releases: true' >> .github/release-drafter.yaml

      - name: Publish draft release
        if: steps.check_draft_release.outputs.published == 'false'
        uses: release-drafter/release-drafter@v5
        with:
          config-name: release-drafter.yaml
          prerelease: ${{ inputs.prerelease }}
          publish: true
          version: ${{ inputs.version }}
          tag: ${{ inputs.version }}
          name: ${{ inputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
