name: _Publish gem

on:
  workflow_call:
    inputs:
      version:
        description: A valid semantic version.
        required: true
        type: string
      gemspec_path:
        description: A path of the gemspec file.
         containing the version string to be updated.
        required: true
        type: string
      checks_watch_start_period:
        description: A duration until to start watching pr checks
        required: false
        type: string
        default: 30s
      checks_watch_interval:
        description: A refresh interval in seconds when watching pr checks
        required: false
        type: string
        default: 120
    secrets:
      pr_create_token:
        description: |
          An access token that can create pull requests.
          NOTICE: secrets.GITHUB_TOKEN cannot be used because the pull request approver must be someone other than the creator.
        required: true

jobs:
  publish_gem:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'

      - name: Configure gem credentials
        run: |
          mkdir -p ~/.gem
          touch ~/.gem/credentials
          chmod 600 ~/.gem/credentials
          echo -e "---\n:github: Bearer ${{ secrets.GITHUB_TOKEN }}" > ~/.gem/credentials

      - name: Get publish gem
        id: get_publish_gem
        run: |
          echo "name=$(sed -n -e "s/[[:blank:]]*.*\.\?[^_]name[[:blank:]]*=[[:blank:]]*['\"]\(.*\)['\"].*/\1/ip" ${{ inputs.gemspec_path }})" >> $GITHUB_OUTPUT
          echo "version=$(echo ${{ inputs.version }} | sed -e 's/^v//' -e 's/^\([[:digit:]]\+\.[[:digit:]]\+\.[[:digit:]]\+\)[-]\?\(.\+\)$/\1.\2/')" >> $GITHUB_OUTPUT

      - name: Check gem on push host
        id: check_gem_on_push_host
        run: |
          ret=$(
          gem search \
          ${{ steps.get_publish_gem.outputs.name }} \
          --quiet \
          --remote \
          --exact \
          --clear-sources \
          --source https://x-access-token:${{ secrets.GITHUB_TOKEN }}@rubygems.pkg.github.com/ych-tnk \
          --version ${{ steps.get_publish_gem.outputs.version }}
          )
          pushed="$(test -n "${ret}" && echo 'true' || echo 'false')"
          if [ "${pushed}" == 'true' ]; then
             echo '::warning::The gem publication skipped because the gem has already been published.'
          fi
          echo "pushed=${pushed}" >> $GITHUB_OUTPUT

      - name: Check gem version
        id: check_gem_vesion
        run: |
          updated="$(test -n "$(grep "[[:blank:]]*.*\.\?[^_]version[[:blank:]]*=[[:blank:]]*'${{ steps.get_publish_gem.outputs.version }}'" ${{ inputs.gemspec_path }})" && echo 'true' || echo 'false')"
          if [ "${updated}" == 'true' ]; then
             echo '::warning::The gem version update skipped because the gem version has already been updated.'
          fi
          echo "updated=${updated}" >> $GITHUB_OUTPUT

      - name: Update gem version
        if: |
          steps.check_gem_on_push_host.outputs.pushed == 'false' &&
          steps.check_gem_vesion.outputs.updated == 'false'
        run: sed -i -e "s/\([[:blank:]]*.*\.\?[^_]version[[:blank:]]*=[[:blank:]]*['\"]\).*\(['\"].*\)/\1${{ steps.get_publish_gem.outputs.version }}\2/i" ${{ inputs.gemspec_path }}

      - name: Create bump pull request
        if: |
          steps.check_gem_on_push_host.outputs.pushed == 'false' &&
          steps.check_gem_vesion.outputs.updated == 'false'
        id: create_bump_pr
        uses: peter-evans/create-pull-request@v5
        with:
          title: Update gem version to ${{ inputs.version }}
          labels: |
            version/patch
            category/misc
          token: ${{ secrets.pr_create_token }}

      - name: Approve pull request
        if: |
          steps.check_gem_on_push_host.outputs.pushed == 'false' &&
          steps.check_gem_vesion.outputs.updated == 'false' &&
          steps.create_bump_pr.outputs.pull-request-operation != ''
        run: gh pr review --approve ${{ steps.create_bump_pr.outputs.pull-request-url }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Wait check complete
        if: |
          steps.check_gem_on_push_host.outputs.pushed == 'false' &&
          steps.check_gem_vesion.outputs.updated == 'false' &&
          steps.create_bump_pr.outputs.pull-request-operation != ''
        run: |
          sleep ${{ inputs.checks_watch_start_period }}
          gh pr checks ${{ steps.create_bump_pr.outputs.pull-request-url }} --required --interval=${{ inputs.checks_watch_interval }} --watch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Merge pull request
        if: |
          steps.check_gem_on_push_host.outputs.pushed == 'false' &&
          steps.check_gem_vesion.outputs.updated == 'false' &&
          steps.create_bump_pr.outputs.pull-request-operation != ''
        run: gh pr merge --merge ${{ steps.create_bump_pr.outputs.pull-request-url }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push gem
        if: steps.check_gem_on_push_host.outputs.pushed == 'false'
        run: |
          gem build ${{ inputs.gemspec_path }}
          gem push --key github --host https://rubygems.pkg.github.com/ych-tnk ${{ steps.get_publish_gem.outputs.name }}-${{ steps.get_publish_gem.outputs.version }}.gem
