name: Auto assign labels to pull requests

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize
      - edited

jobs:
  auto_assign_labels_to_pr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      statuses: write
      checks: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Chack protocol files changed
        uses: dorny/paths-filter@v2
        id: check_proto_files_changed
        with:
          filters: |
            proto:
              - proto/**

      - name: Auto assign labels to pull requests
        uses: fuxingloh/multi-labeler@v2
        with:
          config-path: .github/labeler.yaml

      - name: Auto assign proto labels to pull requests
        if: steps.check_proto_files_changed.outputs.proto == 'true'
        uses: fuxingloh/multi-labeler@v2
        with:
          config-path: .github/proto-labeler.yaml
