name: Check labels
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - labeled
      - unlabeled

jobs:
  check_labels:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Chack files changed
        uses: dorny/paths-filter@v2
        id: check_files_changed
        with:
          filters: |
            proto:
              - proto/**

      - name: Check pr labels
        uses: docker://agilepathway/pull-request-label-checker:latest
        with:
          any_of: pr-category/enhancement,pr-category/improvement,pr-category/hotfix,pr-category/bugfix,pr-category/misc,pr-category/bump
          repo_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check proto labels
        if: steps.check_files_changed.outputs.proto == 'true'
        uses: docker://agilepathway/pull-request-label-checker:latest
        with:
          any_of:  proto-changes/breaking, proto-changes/compatible, proto-changes/dependency
          repo_token: ${{ secrets.GITHUB_TOKEN }}
