name: Create or update draft release 
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize
  workflow_dispatch:

permissions:
  contents: write

jobs:
  crate_update_release_draft:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Create or update draft release 
        uses: release-drafter/release-drafter@v5
        with:
          config-name: release-drafter.yaml
