name: Dispatch release

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: Select a release type
        required: true
        type: choice
        options:
          - 'ga'
          - 'rc'

jobs:
  get_next_release:
    runs-on: ubuntu-latest
    outputs:
      exists: ${{ steps.check_existence_releaseable_differences.outputs.has_diffrences }}
      version: ${{ steps.create_or_update_draft_release.outputs.tag_name }}
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Get latest release tag
        id: get_latest_release_tag
        run: |
          case "${{ github.event.inputs.release_type }}" in
            'ga')
              echo "value=$(gh api /repos/{owner}/{repo}/releases --jq 'first(.[] | select(.prerelease != true) | select(.draft != true)).tag_name')" >> $GITHUB_OUTPUT
              ;;
            'rc')
              echo "value=$(gh api /repos/{owner}/{repo}/releases --jq 'first(.[] | select(.draft != true)).tag_name')" >> $GITHUB_OUTPUT
              ;;
          esac
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check existence of releasable differences
        id: check_existence_releaseable_differences
        run: |
          diff="$(git diff --shortstat ${{ steps.get_latest_release_tag.outputs.value }}...)"
          if [ -n "${diff}" ]; then
            echo "has_diffrences=true" >> $GITHUB_OUTPUT
          else
            case "${{ github.event.inputs.release_type }}" in
              'ga')
                echo "::warning::The GA release publication is skipped because there is no difference between the latest GA release and HEAD."
                ;;
              'rc')
                echo "::warning::The RC release publication is skipped because there is no difference between the latest release and HEAD."
                ;;
            esac
            echo "has_diffrences=false" >> $GITHUB_OUTPUT
          fi

      - name: Create or update draft release
        if: steps.check_existence_releaseable_differences.outputs.has_diffrences == 'true'
        id: create_or_update_draft_release
        uses: release-drafter/release-drafter@master
        with:
          config-name: release-drafter.yaml
          prerelease: ${{ github.event.inputs.release_type != 'ga' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish_gem:
    needs: get_next_release
    if: needs.get_next_release.outputs.exists == 'true'
    uses: ./.github/workflows/_publish_gem.yaml
    permissions:
      contents: write
      pull-requests: write
      packages: write
    with:
      version: ${{ needs.get_next_release.outputs.version }}
      gemspec_path: sandbox.gemspec
    secrets:
      pr_create_token: ${{ secrets.TEST }}

  publish_draft_release:
    needs: 
      - get_next_release
      - publish_gem
    if: needs.get_next_release.outputs.exists == 'true'
    uses: ./.github/workflows/_publish_draft_release.yaml
    permissions:
      contents: write
      pull-requests: write
    with:
      prerelease: ${{ github.event.inputs.release_type != 'ga' }}
      version: ${{ needs.get_next_release.outputs.version }}
