name: Publish gem
on:
  release:
    types: [published]

jobs:
  publish_gem:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.2' 
      - name: Configure gem credentials
        run: |
          mkdir -p ~/.gem
          touch ~/.gem/credentials
          chmod 600 ~/.gem/credentials
          echo -e "---\n:github: Bearer ${{ secrets.GITHUB_TOKEN }}" >> ~/.gem/credentials
      # - name: Build and push gem
      #   run: |
      #     rm -f ${{ inputs.gem }}-*.gem
      #     gem build ${{ inputs.gem }}.gemspec
      #     gem push --key github --host https://rubygems.pkg.github.com/C-FO ${{ inputs.gem }}-*.gem
