name: Replace pull request placeholder

on:
  pull_request:
    branches:
      - main
    types:
      - opened

jobs:
  replace_pr_placeholder:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Chack files changed
        uses: dorny/paths-filter@v2
        id: check_files_changed
        with:
          filters: |
            proto:
              - proto/**
 
      - name: Replace protocol-changes
        if: steps.check_files_changed.outputs.proto == 'true'
        run: |
          replaced="$(gh pr view ${{ github.event.number }} --json body --jq .body | sed -e '/^<!-- protocol-changes/d' -e '/^protocol-changes -->/d'
          gh pr edit ${{ github.event.number }} --body "${replaced}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
