name: Sync labels
on:
  push:
    branches:
      - main
    paths:
      - .github/labels.yaml

permissions:
  contents: read
  pull-requests: write

jobs:
  sync_labels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: micnncim/action-label-syncer@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          manifest: .github/labels.yaml
