name: Sync labels

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/sync_labels.yaml
      - .github/labels.yaml

jobs:
  sync_labels:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Sync labels
        uses: micnncim/action-label-syncer@v1
        with:
          manifest: .github/labels.yaml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
