name: Update gem version

on:
  workflow_call:
    inputs:
      version:
        description: A valid semantic version.
        required: true
        type: string
      version_file:
        description: A path of the file containing the version string to be updated.
        required: true
        type: string
    secrets:
      pr_approvable_token:
        description: |
          An access token that can approve pull requests.
          NOTICE: secrets.GITHUB_TOKEN cannot be used because the pull request approver must be someone other than the creator.
        required: true

jobs:
  update_gem_version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update gem version
        run: |
          gem_format_version=$(echo ${{ inputs.version }} | sed -e 's/^v//' -e 's/^\([[:digit:]]\+\.[[:digit:]]\+\.[[:digit:]]\+\)[-]\?\(.\+\)$/\1.\2/')
          sed -i -e "s/\([[:blank:]]*.*\.\?version[[:blank:]]*=[[:blank:]]['\"]\).\+\(['\"].*\)/\1${gem_format_version}\2/i" ${{ inpus.version_file }}

      - name: Create pull request
        id: create_bump_up_pr
        uses: peter-evans/create-pull-request@v5
        with:
          title: Update gem version to ${{ inputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Approve pull request
        run: gh pr review --approve ${{ steps.create_bump_up_pr.outputs.pull-request-url }}
        env:
          GITHUB_TOKEN: ${{ inputs.pr_approvable_token }}

      - name: Merge pull request
        run: gh pr merge --merge --auto ${{ steps.create_bump_up_pr.outputs.pull-request-url }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
